# Filename: docker-compose.prod.yml
# Author: Pranav Pawar
# Description: Docker Compose for local run

version: '1.0'

services:
  web:
    build: 
      context: .
      dockerfile: docker/backend/Dockerfile
    command: gunicorn portfolio.wsgi:application --workers 1 --worker-class=gevent --bind 0.0.0.0:8000 --timeout 120
    ports:
      - "8000:8000"
    volumes:
      - static:/usr/src/app/backend/build
    env_file:
      - ./.env.local
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    networks:
      - app-network

  nginx:
    build: 
      context: .
      dockerfile: docker/nginx/Dockerfile  
    ports:
      - 80:8080
    volumes:
      - static:/var/www/react
    depends_on:
      - web
    networks:
      - app-network

  celery:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    command: celery -A portfolio.celery worker --pool=solo -l info
    env_file:
      - ./.env.local
    depends_on:
      - web
    networks:
      - app-network

  celery-beat:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    command: celery -A portfolio beat -l info
    env_file:
      - ./.env.local
    depends_on:
      - web
    networks:
      - app-network

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  static:

  